name: CI-macOS

on:
  push:
    branches: [ "7_45_3_3161" ]
    paths-ignore:
    - '.github/workflows/ci.yml'
    - '.github/workflows/ci-windows.yml'
    - '.github/workflows/cibuildwheel.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.github/workflows/ci.yml'
    - '.github/workflows/ci-windows.yml'
    - '.github/workflows/cibuildwheel.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macOS-12
    env:
      PYCURL_CURL_CONFIG: /usr/bin/curl-config
      PYCURL_SSL_LIBRARY: sectransp
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.2"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Build
      run: make
    - name: Test with pytest
      run: make test
